server:
  port: 3344
spring:
  application:
    name:  cloud-config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: git@github.com:sunxian/springcloud-config.git
          search-paths:
              springcloud-config
          default-label: main


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka



#暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        #include: 'bus-refresh'
         include: '*'